-- CREATE TABLE Person_Drug (
--     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     person_id int REFERENCES Person(id),
--     drug_id int REFERENCES Drug(id),
--     dose varchar(20),
--     period varchar(20),
--     start_date DATE NOT NULL,
--     end_date DATE NOT NULL
-- );

-- INSERT INTO Person_Drug(person_id, drug_id, dose, period, start_date, end_date) 
--      VALUES (2, 5, 'Доза лекарства', 'Период', '2024-05-21', '2024-05-30');

select * from Person_Drug;

-- DROP TABLE Person_Drug;
DELETE FROM Person_Drug WHERE id=3;


